<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CIPSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('cip')->insert([
            
            'created_at' => date('Y-m-d H:i:s'),
            'assetCodeEnginery' =>'3001470-5',
            'assetCategory' =>'Machine',
            'assetClass' =>'302',
            'assetGroup' =>'Machine1',
            'assetDescription' =>'M/C Damper Assembly Machine HvD 22MY',
            'subAsset' =>'1',
            'picAsset' =>'SPV Engineering',
            'cipCode' =>'1220184',
            'acquisitionCIP' => date('2018-04-14'),
            'depreciationStart' => date('2018-05-04'),
            'depreciationEnd' => date('2025-05-03'),
            'currentBookValue' =>'512000000',
            'assetCondition' =>'Good',
            'assetStatus' =>'Active',
            'costCenter' =>'ENG331',
            'product' =>'Hybrid Damper',
            'inventoryNumber'=> null,
            'department' =>'Engineering Body',
            'vendor' =>'PT Chemicon',
            'site' =>'Plant 1',
            'line' =>'ASDL01',
            'proccess' =>'Apply Grease Housing',
            'quantity' =>'1',
            'uom' =>'pcs',
            'acquisitionValue' =>'512000000',
            'cipNumber'=> null,
            'budgetNumber' =>'CC12001',
            'poNumber' =>'PO12012018',
            'assetPicture'=>null,
            'statusRequest' => false,
            'statusConfirmation'=> false,
            'outstandingStatus'=> false,
        ]);
        DB::table('cip')->insert([
            
            'created_at' => date('Y-m-d H:i:s'),
            'assetCodeEnginery' =>'3001470-6',
            'assetCategory' =>'Machine',
            'assetClass' =>'302',
            'assetGroup' =>'Machine1',
            'assetDescription' =>'M/C Damper Assembly Machine HvD 22MY',
            'subAsset' =>'1',
            'picAsset' =>'SPV Engineering',
            'cipCode' =>'1220184',
            'acquisitionCIP' => date('2018-04-14'),
            'depreciationStart' => date('2018-05-04'),
            'depreciationEnd' => date('2025-05-03'),
            'currentBookValue' =>'512000000',
            'assetCondition' =>'Good',
            'assetStatus' =>'Active',
            'costCenter' =>'ENG331',
            'product' =>'Hybrid Damper',
            'inventoryNumber'=> null,
            'department' =>'Engineering Body',
            'vendor' =>'PT Chemicon',
            'site' =>'Plant 1',
            'line' =>'ASDL01',
            'proccess' =>'Apply Grease Housing',
            'quantity' =>'1',
            'uom' =>'pcs',
            'acquisitionValue' =>'512000000',
            'cipNumber'=> null,
            'budgetNumber' =>'CC12001',
            'poNumber' =>'PO12012018',
            'assetPicture'=>null,
            'statusRequest' => false,
            'statusConfirmation'=> false,
            'outstandingStatus'=> false,
        ]);
        DB::table('cip')->insert([
            
            'created_at' => date('Y-m-d H:i:s'),
            'assetCodeEnginery' =>'3001470-7',
            'assetCategory' =>'Machine',
            'assetClass' =>'302',
            'assetGroup' =>'Machine1',
            'assetDescription' =>'M/C Damper Assembly Machine HvD 22MY',
            'subAsset' =>'1',
            'picAsset' =>'SPV Engineering',
            'cipCode' =>'1220184',
            'acquisitionCIP' => date('2018-04-14'),
            'depreciationStart' => date('2018-05-04'),
            'depreciationEnd' => date('2025-05-03'),
            'currentBookValue' =>'512000000',
            'assetCondition' =>'Good',
            'assetStatus' =>'Active',
            'costCenter' =>'ENG331',
            'product' =>'Hybrid Damper',
            'inventoryNumber'=> null,
            'department' =>'Engineering Body',
            'vendor' =>'PT Chemicon',
            'site' =>'Plant 1',
            'line' =>'ASDL01',
            'proccess' =>'Apply Grease Housing',
            'quantity' =>'1',
            'uom' =>'pcs',
            'acquisitionValue' =>'512000000',
            'cipNumber'=> null,
            'budgetNumber' =>'CC12001',
            'poNumber' =>'PO12012018',
            'assetPicture'=>null,
            'statusRequest' => false,
            'statusConfirmation'=> false,
            'outstandingStatus'=> false,
        ]);
        DB::table('cip')->insert([
            
            'created_at' => date('Y-m-d H:i:s'),
            'assetCodeEnginery' =>'3001470-8',
            'assetCategory' =>'Machine',
            'assetClass' =>'302',
            'assetGroup' =>'Machine1',
            'assetDescription' =>'M/C Damper Assembly Machine HvD 22MY',
            'subAsset' =>'1',
            'picAsset' =>'SPV Engineering',
            'cipCode' =>'1220184',
            'acquisitionCIP' => date('2018-04-14'),
            'depreciationStart' => date('2018-05-04'),
            'depreciationEnd' => date('2025-05-03'),
            'currentBookValue' =>'512000000',
            'assetCondition' =>'Good',
            'assetStatus' =>'Active',
            'costCenter' =>'ENG331',
            'product' =>'Hybrid Damper',
            'inventoryNumber'=> null,
            'department' =>'Engineering Body',
            'vendor' =>'PT Chemicon',
            'site' =>'Plant 1',
            'line' =>'ASDL01',
            'proccess' =>'Apply Grease Housing',
            'quantity' =>'1',
            'uom' =>'pcs',
            'acquisitionValue' =>'512000000',
            'cipNumber'=> null,
            'budgetNumber' =>'CC12001',
            'poNumber' =>'PO12012018',
            'assetPicture'=>null,
            'statusRequest' => false,
            'statusConfirmation'=> false,
            'outstandingStatus'=> false,
        ]);
        DB::table('cip')->insert([
            
            'created_at' => date('Y-m-d H:i:s'),
            'assetCodeEnginery' =>'3001470-9',
            'assetCategory' =>'Machine',
            'assetClass' =>'302',
            'assetGroup' =>'Machine1',
            'assetDescription' =>'M/C Damper Assembly Machine HvD 22MY',
            'subAsset' =>'1',
            'picAsset' =>'SPV Engineering',
            'cipCode' =>'1220184',
            'acquisitionCIP' => date('2018-04-14'),
            'depreciationStart' => date('2018-05-04'),
            'depreciationEnd' => date('2025-05-03'),
            'currentBookValue' =>'512000000',
            'assetCondition' =>'Good',
            'assetStatus' =>'Active',
            'costCenter' =>'ENG331',
            'product' =>'Hybrid Damper',
            'inventoryNumber'=> null,
            'department' =>'Engineering Body',
            'vendor' =>'PT Chemicon',
            'site' =>'Plant 1',
            'line' =>'ASDL01',
            'proccess' =>'Apply Grease Housing',
            'quantity' =>'1',
            'uom' =>'pcs',
            'acquisitionValue' =>'512000000',
            'cipNumber'=> null,
            'budgetNumber' =>'CC12001',
            'poNumber' =>'PO12012018',
            'assetPicture'=>null,
            'statusRequest' => false,
            'statusConfirmation'=> false,
            'outstandingStatus'=> false,
        ]);
    }
}
